include: package:workiva_analysis_options/v2.yaml
analyzer:
  errors:
    unused_import: warning
    duplicate_import: warning
    missing_required_param: error
    must_call_super: error
  strong-mode:
    implicit-casts: false
